### ISSUE TITLE
Ensemble doesn't tell you to enable other ENV

### ISSUE THREAD

**Issue by Jamesking56** [simonhamp/ensemble-plugin#3]
The Ensemble website tells you to set your `ENSEMBLE_PRIVATE_KEY` variable but doesn't tell you that you also need `ENSEMBLE_ENABLED` set to `true`.

The website should add that in.

**Comment by simonhamp** [comment]
This is a good point. It's only in the [plugin README](https://github.com/simonhamp/ensemble-plugin) at the moment. I will fix this ;)

**Comment by simonhamp** [comment]
This has been updated (finally!)
