### ISSUE TITLE
Can no longer install ensemble-plugin

### ISSUE THREAD

**Issue by Jamesking56** [simonhamp/ensemble-plugin#6]
When I now do `composer require simonhamp/ensemble-plugin` I get:

````
Using version ^1.2 for simonhamp/ensemble-plugin         
./composer.json has been updated
Loading composer repositories with package information                                                                                                                                               Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - simonhamp/ensemble-plugin v1.2.1 requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master] but these conflict with your requirements or minimum-stability.
    - simonhamp/ensemble-plugin v1.2.0 requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master] but these conflict with your requirements or minimum-stability.
    - Installation request for simonhamp/ensemble-plugin ^1.2 -> satisfiable by simonhamp/ensemble-plugin[v1.2.0, v1.2.1].


Installation failed, reverting ./composer.json to its original content.
````

**Comment by Jamesking56** [comment]
@simonhamp ?

**Comment by simonhamp** [comment]
It looks like your dependencies are clashing with the `roave/security-advisories` meta package. What's the `minimum-stability` setting in your project's `composer.json`?

If there isn't one, I'd recommend adding it, as the default is [`stable`](https://getcomposer.org/doc/04-schema.md#minimum-stability) and incompatible with that package.

Like this: `"minimum-stability": "dev"`.

Please add that and let me know how you get on.

**Comment by simonhamp** [comment]
If that's not an option, you can require that package as a direct dev dependency of your project:
`composer require --dev roave/security-advisories:dev-master`

**Comment by simonhamp** [comment]
@Jamesking56 how did you get on with this?
